//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fubon_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOrder
    {
        public string OrderNo { get; set; }
        public short OrderState { get; set; }
        public string ResultCode { get; set; }
        public string StoreId { get; set; }
        public string StoreRefNo { get; set; }
        public string PayerId { get; set; }
        public string SchemeId { get; set; }
        public string PayerRefNo { get; set; }
        public string BuyerId { get; set; }
        public string BuyerName { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhoneNo { get; set; }
        public string CustomerPhoneNo2 { get; set; }
        public string CustomerEmail { get; set; }
        public System.DateTime OrderTime { get; set; }
        public string OrderName { get; set; }
        public string OrderDesc { get; set; }
        public bool ShipFree { get; set; }
        public int CustomerShipFee { get; set; }
        public int SellerShipFee { get; set; }
        public string SellerCurrency { get; set; }
        public decimal SellerAmount { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal ExchangeRisk { get; set; }
        public decimal SBRate { get; set; }
        public decimal BaseAmount { get; set; }
        public string PayerCurrency { get; set; }
        public decimal BPRate { get; set; }
        public decimal PayerAmount { get; set; }
        public string PaymentTime { get; set; }
        public string SettleTime { get; set; }
        public short ShipState { get; set; }
        public string ExpressId { get; set; }
        public string ShipNo { get; set; }
        public short ShipKind { get; set; }
        public bool ReceiveTime1 { get; set; }
        public bool ReceiveTime2 { get; set; }
        public bool ReceiveTime3 { get; set; }
        public string AreaCode { get; set; }
        public string AreaName { get; set; }
        public string ShipAddr2 { get; set; }
        public string ShipAddress { get; set; }
        public string DisburseNo { get; set; }
        public short RefundState { get; set; }
        public decimal F2Rate { get; set; }
        public decimal StoreServiceFeeRate { get; set; }
        public decimal ExpressServiceFeeRate { get; set; }
        public decimal PayerServiceFee { get; set; }
        public decimal BankServiceFee { get; set; }
        public decimal StoreServiceFee { get; set; }
        public decimal ExpressServiceFee { get; set; }
        public decimal StoreNetAmount { get; set; }
        public string ReceivingPaperImage { get; set; }
        public string DeliveryAddress { get; set; }
        public string DeliveryDateTime { get; set; }
        public Nullable<System.DateTime> DeliveryNotifyTime { get; set; }
        public short Packages { get; set; }
        public string IPAddress { get; set; }
        public string SubStoreId { get; set; }
        public string ttime { get; set; }
        public string SsoRef { get; set; }
        public string Token { get; set; }
        public string ReturnUrl { get; set; }
        public Nullable<System.DateTime> NotifyTime { get; set; }
        public string BankType { get; set; }
        public string ClientAction { get; set; }
        public string ClientDevice { get; set; }
        public string ClientVersion { get; set; }
        public string DeviceLocation { get; set; }
        public string ExtractPaperImage { get; set; }
        public string SnapshotFile { get; set; }
        public long rowid { get; set; }
        public decimal ChannelFee { get; set; }
        public string BankRemark { get; set; }
        public bool IsAdvance { get; set; }
        public string BaseCurrency { get; set; }
        public string DeviceId { get; set; }
        public string AuthCode { get; set; }
        public string ExtData { get; set; }
        public System.DateTime StoreTime { get; set; }
        public string CancelNo { get; set; }
        public Nullable<System.DateTime> CancelTime { get; set; }
        public decimal CancelFee { get; set; }
        public short StoreOrderState { get; set; }
        public Nullable<System.DateTime> TNDate { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
