//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fubon_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Store()
        {
            this.SaleOrder = new HashSet<SaleOrder>();
        }
    
        public string StoreId { get; set; }
        public string StoreName { get; set; }
        public string UBN { get; set; }
        public string StoreKind { get; set; }
        public string ApplyKind { get; set; }
        public string BusinessName { get; set; }
        public string BossName { get; set; }
        public string BossSid { get; set; }
        public string RegistAddress { get; set; }
        public string BusinessAddress { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string WebSite { get; set; }
        public string IPAddress { get; set; }
        public string SalesContact { get; set; }
        public string SalesTel { get; set; }
        public string SalesEmail { get; set; }
        public string BillingContact { get; set; }
        public string BillingTel { get; set; }
        public string BillingEmail { get; set; }
        public string ServiceContact { get; set; }
        public string ServiceTel { get; set; }
        public string ServiceEmail { get; set; }
        public string EMallId { get; set; }
        public string EMallName { get; set; }
        public string ExpressId { get; set; }
        public string QueryUrl { get; set; }
        public string ProductUrl { get; set; }
        public string NotifyUrl { get; set; }
        public string FtpUrl { get; set; }
        public string FtpUserId { get; set; }
        public string FtpPassword { get; set; }
        public bool IsRedirect { get; set; }
        public string BankBranchNo { get; set; }
        public string BankAccountNo { get; set; }
        public decimal FeeRate { get; set; }
        public int AnnualFee { get; set; }
        public bool IsNoFirstAnnualFee { get; set; }
        public string StartDate { get; set; }
        public string DueDate { get; set; }
        public short State { get; set; }
        public string StateDesc { get; set; }
        public string DeliveryAddress { get; set; }
        public string StoreType { get; set; }
        public string Note { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateUserId { get; set; }
        public System.DateTime Lastupdate { get; set; }
        public string UpdateUserId { get; set; }
        public short EtaoState { get; set; }
        public string EtaoDenyDesc { get; set; }
        public string SsoUrl { get; set; }
        public bool IsSynchroUpload { get; set; }
        public long rowid { get; set; }
        public string PaymentCycle { get; set; }
        public int PaymentCycleDay { get; set; }
        public int PaymentCycleWeek { get; set; }
        public string BussinessTimeOpen { get; set; }
        public string BussinessTimeClose { get; set; }
        public int DeviceProvide { get; set; }
        public string Manufacturers { get; set; }
        public int TerminalQuantity { get; set; }
        public int ConnectionLimit { get; set; }
        public int TerminalCost { get; set; }
        public int CashPledge { get; set; }
        public bool IsCashPledge { get; set; }
        public string RefundAccountNo { get; set; }
        public string DeviceListType { get; set; }
        public string sub_mch_id { get; set; }
        public string DisburseReconType { get; set; }
        public decimal ExchangeRisk { get; set; }
        public bool IsLockIPAddress { get; set; }
        public string PublicKey { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleOrder> SaleOrder { get; set; }
        public virtual Store Store1 { get; set; }
        public virtual Store Store2 { get; set; }
    }
}
